import fhaaaaSound from './assets/fhaaaa.mp3';

export const ALARM_SOUNDS = [
  { id: 'default', name: 'Default Chime', url: '' },
  { id: 'bells', name: 'Morning Bells', url: '' },
  { id: 'birds', name: 'Birdsong', url: '' },
  { id: 'digital', name: 'Digital Beep', url: '' },
  { id: 'gentle', name: 'Gentle Wake', url: '' },
  { id: 'high_freq_1', name: 'Crystal Pulse', url: '' },
  { id: 'high_freq_2', name: 'Starlight Ping', url: '' },
  { id: 'high_freq_3', name: 'Laser Beam', url: '' },
  { id: 'high_freq_4', name: 'Neon Siren', url: '' },
  { id: 'high_freq_5', name: 'Glass Chime', url: '' },
  { id: 'high_freq_6', name: 'High Pitch Whine', url: '' },
  { id: 'high_freq_7', name: 'Ultrasonic Wave', url: '' },
  { id: 'high_freq_8', name: 'Space Sweep', url: '' },
  { id: 'high_freq_9', name: 'Rapid Blasts', url: '' },
  { id: 'high_freq_10', name: 'Emergency Alert', url: '' },
  { id: 'loud_beep_1', name: 'Classic Clock', url: '' },
  { id: 'loud_beep_2', name: 'Double Strike', url: '' },
  { id: 'loud_beep_3', name: 'Machine Gun Beeps', url: '' },
  { id: 'loud_beep_4', name: 'Ear Piercer', url: '' },
  { id: 'loud_beep_5', name: 'Klaxon Warning', url: '' },
  { id: 'heavy_loud_1', name: 'Thunder Strike', url: '' },
  { id: 'heavy_loud_2', name: 'Reactor Warning', url: '' },
  { id: 'heavy_loud_3', name: 'Air Raid', url: '' },
  { id: 'heavy_loud_4', name: 'Heavy Machine Gun', url: '' },
  { id: 'heavy_loud_5', name: 'Tornado Siren', url: '' },
  { id: 'marimba', name: 'Marimba', url: '' },
  { id: 'ocean', name: 'Ocean Waves', url: '' },
  { id: 'piano', name: 'Piano Melody', url: '' },
  { id: 'rooster', name: 'Rooster Crow', url: '' },
  { id: 'synth', name: 'Synth Pop', url: '' },
  { id: 'fhaaaa', name: 'Fhaaaa Meme', url: fhaaaaSound },
  { id: 'custom', name: 'Custom Ringtone', url: 'custom' }
];

export const LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'hi', name: 'Hindi (हिंदी)' },
  { code: 'bn', name: 'Bengali (বাংলা)' },
  { code: 'te', name: 'Telugu (తెలుగు)' },
  { code: 'mr', name: 'Marathi (मराठी)' },
  { code: 'ta', name: 'Tamil (தமிழ்)' },
  { code: 'ur', name: 'Urdu (اردو)' },
  { code: 'gu', name: 'Gujarati (ગુજરાતી)' },
  { code: 'kn', name: 'Kannada (ಕನ್ನಡ)' },
  { code: 'ml', name: 'Malayalam (മലയാളം)' },
  { code: 'pa', name: 'Punjabi (ਪੰਜਾਬੀ)' },
  { code: 'es', name: 'Spanish (Español)' },
  { code: 'fr', name: 'French (Français)' },
  { code: 'de', name: 'German (Deutsch)' },
  { code: 'zh', name: 'Chinese (中文)' },
  { code: 'ja', name: 'Japanese (日本語)' },
  { code: 'ar', name: 'Arabic (العربية)' },
];
